/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rsm_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[9] = {4, 2, 0, 2, 4, 1, 2, 0, 3};
static const casadi_int casadi_s3[7] = {4, 2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s4[11] = {4, 2, 0, 3, 6, 0, 2, 3, 1, 2, 3};

/* rsm_impl_dae_jac_x_xdot_u_z:(i0[2],i1[2],i2[2],i3[2],i4[3])->(o0[4x2,4nz],o1[4x2,2nz],o2[4x2,2nz],o3[4x2,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[4]? arg[4][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=1.;
  if (res[0]!=0) res[0][1]=a1;
  a0=(-a0);
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a1;
  if (res[1]!=0) res[1][0]=a1;
  if (res[1]!=0) res[1][1]=a1;
  a0=-1.;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  a0=4.0000000000000002e-01;
  if (res[3]!=0) res[3][0]=a0;
  a2=-4.2158580856399789e-03;
  a3=8.8347386941151085e-01;
  a4=-8.4134931517219783e-05;
  a5=arg[3]? arg[3][1] : 0;
  a6=casadi_sq(a5);
  a6=(a4*a6);
  a6=exp(a6);
  a7=1.4168340852826439e-01;
  a8=arg[3]? arg[3][0] : 0;
  a9=(a7*a8);
  a10=casadi_sq(a9);
  a10=(a1+a10);
  a7=(a7/a10);
  a7=(a6*a7);
  a7=(a3*a7);
  a2=(a2+a7);
  a2=(-a2);
  if (res[3]!=0) res[3][1]=a2;
  a2=6.6490363510628120e-02;
  a7=atan(a5);
  a10=-1.3888888888888888e-02;
  a11=casadi_sq(a8);
  a11=(a10*a11);
  a11=exp(a11);
  a8=(a8+a8);
  a10=(a10*a8);
  a10=(a11*a10);
  a7=(a7*a10);
  a7=(a2*a7);
  a7=(-a7);
  if (res[3]!=0) res[3][2]=a7;
  if (res[3]!=0) res[3][3]=a0;
  a9=atan(a9);
  a0=(a5+a5);
  a4=(a4*a0);
  a6=(a6*a4);
  a9=(a9*a6);
  a3=(a3*a9);
  a3=(-a3);
  if (res[3]!=0) res[3][4]=a3;
  a3=1.0448833570264901e-02;
  a5=casadi_sq(a5);
  a1=(a1+a5);
  a11=(a11/a1);
  a2=(a2*a11);
  a3=(a3+a2);
  a3=(-a3);
  if (res[3]!=0) res[3][5]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int rsm_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rsm_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rsm_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rsm_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rsm_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rsm_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rsm_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void rsm_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rsm_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rsm_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real rsm_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rsm_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rsm_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rsm_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rsm_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rsm_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
